stages:
  - build
  - run

# Stage 1: Build Docker image
build_image:
  stage: build
  image: docker:latest
  services:
    - docker:20.10.7-dind
  script:
    - echo "Building Docker image with OpenJDK"
    - docker build -t my-java-app .

# Stage 2: Run the application in Docker container
run_application:
  stage: run
  image: docker:latest
  services:
    - docker:20.10.7-dind
  script:
    - echo "Running the application in Docker container"
    - docker run --rm my-java-app