stages:
  - run

# Stage 2: Run the application in Docker container
run_application:
  stage: run
  tags: [ubuntu-shell]
  image: docker:latest
  services:
    - docker:20.10.7-dind
  script:
    - echo "Running script"
    - bash ~/.ci/builder.sh