include:
    - 'Workflows/.gitlab-tmpl-homepage-deploy.yml'

workflow:
  rules:
   - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'
   - when: always

default:
    tags:
    - ubuntu-shell
    retry: 2
    timeout: 1m

variables:
    NAME: "vasya"
    PAGE_TEXT: "Hello from reusable workflow"
    ENVIRONMENT:
      value: DEV
      options:
      - DEV
      - STG
      - PRD

stages:
  - validate
  - clone
  - unit_tests
  - build
  - push
  - deploy
 

validate_params:
    stage: validate
    script:
    - |
      if [ -z "$ENVIRONMENT" ]; then
        echo "ENV is not defined"
        exit 1
      fi
      if [[ "$CI_PIPELINE_SOURCE" == "web" ]]; then
        export NAME="${NAME:-Vlad}"
        export PAGE_TEXT="${PAGE_TEXT:-Привет из шаблона пайплайна}"
      else
        export NAME="${NAME:-Default auto name}"
        export PAGE_TEXT="${PAGE_TEXT:-Default auto text}"
      fi
    - echo "Переменные:"
    - echo "ENVIRONMENT=$ENVIRONMENT"
    - echo "NAME=$NAME"
    - echo "PAGE_TEXT=$PAGE_TEXT"